version: "3"
services:
  database:
    image: groonga/pgroonga
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  codimd:
    # you can use image or custom build below,
    image: hackmdio/codimd
    # build:
    #   context: ..
    #   dockerfile: ./deployments/Dockerfile
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
      - CMD_ALLOW_FREEURL=true
      - CMD_AUTO_VERSION_CHECK=false
      - CMD_ALLOW_PDF_EXPORT=false
    depends_on:
      - database
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
  proxy:
    image: nginx:alpine
    depends_on:
      - codimd
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/ssl/server.crt
      - ./server.key:/etc/ssl/server.key
    ports:
      - "3000:443"
volumes:
  database-data: {}
  upload-data: {}
